version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: stop.sh
      runas: ec2-user
  BeforeInstall:
    - location: cicd/before_install.sh
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      runas: ec2-user
